version: '3.8'

services:
  web:
    build: .
    container_name: bookstore
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - DB_PATH=/app/books.db
      - FLASK_ENV=development
      - PYTHONUNBUFFERED=1
    command: python app.py